# -*- coding: utf-8 -*-
"""German_credit_data_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14krRn9XIrcpoK02warE4pRCk17ku-K_3
"""

from google.colab import drive
drive.mount('/content/drive')

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency
import statsmodels.formula.api as smf

from scipy.io import arff
import pandas as pd

#file_path = "/content/drive/MyDrive/CIND119 Group Assignment/german_credit.csv"

#File Path particular to My local drive
file_path = "/content/drive/MyDrive/CIND 119 Group Assignment/german_credit.csv"

# 1. Load the file (this handles the metadata automatically)
data, meta = arff.loadarff(file_path)

# 2. Convert to DataFrame (meta.names() provides the headers)
df = pd.DataFrame(data)


# 3. Clean up byte strings (ARFF often loads text as b'value')
for col in df.select_dtypes([object]):
    df[col] = df[col].str.decode('utf-8')

print(df.head())

"""Quick Summary of Rows, Attriubutes and Datatypes"""

print(f"Number of rows: {df.shape[0]}")
print(f"Number of attributes: {df.shape[1]}")
print(df.dtypes.value_counts())

"""Summary of the Attributes with Data Types, Missing Value Counts, and Unique Value Counts"""

summary_german_data= pd.DataFrame({"Data Type": df.dtypes, "Missing Values": df.isnull().sum(), "Unique Values": df.nunique()})
print(summary_german_data)

print(df['Duration of Credit (month)'].unique())

"""Numeric Attributes Summary"""

summary = df.describe()
print(summary)

"""Cleaner View of Numeric Attributes with Basic Stats"""

stats_to_compute = ['mean', 'median', 'std', 'min', 'max']

# 2. Create the summary dataframe
# We use .select_dtypes('number') to ensure we don't try to get the mean of text
summary_numerical__df = df.select_dtypes('number').agg(stats_to_compute).T

# 3. Mode is tricky because one column can have multiple modes.
# We add it separately to keep the table clean.
summary_numerical__df['mode'] = df.select_dtypes('number').mode().iloc[0]

# 4. Rename columns for a professional look
summary_numerical__df.columns = ['Mean', 'Median', 'Std Dev', 'Min', 'Max', 'Mode']

# Display the clean table
summary_numerical__df

print(df.columns.tolist())

"""Data Dictionary (Non-Numeric Attributes)"""

#cols_to_fix = ["Creditability", "Account Balance", "Payment Status of Previous Credit",
               #"Value Savings/Stocks", "Sex & Marital Status", "Type of apartment"]

#for col in cols_to_fix:
    #if col in df.columns:
        #df[col] = pd.to_numeric(df[col], errors='coerce')

mapping_dictionary = {
   'Creditability': {1: "Good Credit", 0: "Bad Credit"},
   'Account Balance': {1: "< 0 DM ", 2: "0 <= < 200 DM", 3: "> 200 DM", 4: "No Checking Account"},
   'Payment Status of Previous Credit': {0: "No Credits Taken", 1: "All Credits At This Bank Paid Back Duly", 2: "Existing Credits Paid Back Duly Until Now", 3: "Delay In Paying Off In The Past", 4: "Critical Account/Other Credits Delinquent"},
   'Purpose': {0: "New Car", 1: " Used Car", 2: "Furniture/Equipment", 3: " Radio/TV", 4: " Domestic Appliances", 5: "Repairs", 6: "Education", 7: "Vacation", 8: "Retraining", 9: "Business", 10: "Other"},
   'Value Savings/Stocks': {1: "< 100 DM", 2: "100 <= < 500 DM", 3: "500<= < 1000 DM", 4: "=> 1000 DM", 5: "Unknown/No Savings"},
   'Length of Current Employment': {1: "Unemployed", 2: "< 1 year", 3: "1 <= < 4 years", 4: "4 <= < 7 years", 5: "=> 7 years"},
   'Sex & Marital Status': {1: "male: divorced/separated", 2: "Female: divorced/separated/married", 3:"male: single", 4:"male: married/widowed", 5:"female: single"},
   'Guarantors': {1: "none", 2: "co-applicant", 3: "guarantor"},
   'Duration in Current Address': {1: "<= 1", 2: "1< <= 2 years", 3: "2 <= 3 years", 4: ">3 years"},
   'Most valuable available asset': {1: "real estate", 2: "Savings agreement/life insurance", 3: "car or other", 4: "unknown/no property"},
   'Concurrent Credits': {1: "Bank", 2: "Stores", 3: "None"},
   'Type of apartment': {1: "rent", 2: "own", 3: "for free"},
   'Occupation': {1: "unemployed/unskilled- non-resident", 2: "unskilled resident", 3:"skilled employee / official", 4: "management/ self-employed/highly qualified employee/ officer"},
   'Telephone': {1: "yes", 2:"No"},
  'Foreign Worker': {1: "Yes", 2:"No"}
}

flattened_data = []
for attribute, mappings in mapping_dictionary.items():
    for code, explanation in mappings.items():
        flattened_data.append({"Attribute": attribute, "Code": code, "Explanation": explanation})

# Create the DataFrame
Data_Dictionary = pd.DataFrame(flattened_data)

# Display as a clean grid
Data_Dictionary

#for column, labels in mapping_dictionary.items():
    #if column in df.columns:
        #df[column] = df[column].map(labels)

#print(df.head())

"""Correlation Matrix for all Attributes with Creditability as the target"""

correlation_with_target = df.corr()['Creditability'].sort_values(ascending=False)
print(correlation_with_target)

# 1. Convert the Series to a DataFrame
corr_df = correlation_with_target.reset_index()

# 2. Rename columns for clarity
corr_df.columns = ['Attribute', 'Correlation with Creditability']

# 3. Apply styling (Background gradient makes it "pop" for reports)
styled_corr = corr_df.style.background_gradient(cmap='RdYlGn').format({'Correlation with Creditability': '{:.4f}'})

# 4. Display the grid
styled_corr

"""Strongest positive correlation for Good Credit: Account Balance: 0.35 and Payment Status of Previous Credit: .228. So as Account Balance code increases, the likelihood of Good Credit increases (code 4: No Checking Account does not necessarily mean "No wealth").

 Payment Status of Previous Credit are categorical values that are not neccesarily linear, but since the higher values of "4" also has a large percentage of "Good Credit" it associates codes of higher value as postively correlated to Good Credit".

 Strongest Negative correlation for Good Credit: Duration of Credit: -0.21 and Credit Amount: -0.15. So credit gets riskier the higher the $ amount and the longer the duration of the credit.
"""

# Group by the status and count the Creditability values
status_counts = df.groupby('Payment Status of Previous Credit')['Creditability'].value_counts().unstack().fillna(0)

# Rename columns for clarity
status_counts.columns = ['Bad Credit (0)', 'Good Credit (1)']
print(status_counts)

# Group by the status and count the Creditability values
_status_counts = df.groupby('Account Balance')['Creditability'].value_counts().unstack().fillna(0)

# Rename columns for clarity
_status_counts.columns = ['Bad Credit (0)', 'Good Credit (1)']
print(_status_counts)

# 1. Increase the figure size significantly so labels don't overlap
plt.figure(figsize=(16, 12))

# 2. Calculate correlation for the entire dataframe
# If you have non-numeric columns, use: df.select_dtypes(include='number').corr()
full_corr = df.corr()

# 3. Create the heatmap
# annot=True adds the numbers; fmt=".2f" rounds them to 2 decimals
sns.heatmap(full_corr, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            annot_kws={"size": 8}) # Smaller font for the numbers

plt.title("Full Pearson Correlation Matrix (German Credit)", fontsize=16)
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Full Pearson Correlation Matrix.png', dpi=300, bbox_inches='tight')
plt.show()

"""Pairwise Scatterplot"""

sns.pairplot(df[["Duration of Credit (month)", "Credit Amount", "Age (years)"]],
             kind="reg",
             diag_kind="kde",
             plot_kws={'line_kws':{'color':'red'}, 'scatter_kws': {'alpha': 0.5}})

plt.suptitle("Pairwise Scatterplots with Trend Lines", y=1.02)
plt.show()

attribute = 'Account Balance'
target = 'Credit Amount'

plt.figure(figsize=(12, 6))

# Define your order and labels
desired_order = ["1", "2", "3", "4"]
labels = [
    "1- Less than 0 DM",
    "2- 0 to 200 DM",
    "3- Greater than 200 DM",
    "4- No Account"
]

# Create the boxplot
ax = sns.boxplot(
    data=df,
    x=attribute,
    y=target,
    palette="viridis",
    order=desired_order
)

# Set the descriptive labels on the x-axis
ax.set_xticklabels(labels)

plt.title(f"Distribution of {target} by {attribute}")
plt.xlabel("Account Balance")
plt.ylabel(f"{target} (DM)")
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Credit_Amount_vs_Account Balance.png', dpi=300, bbox_inches='tight')

plt.show()

attribute = 'Account Balance'
target = 'Duration of Credit (month)'

plt.figure(figsize=(12, 6))

# Define your order and labels
desired_order = ["1", "2", "3", "4"]
labels = [
    "1- Less than 0 DM",
    "2- 0 to 200 DM",
    "3- Greater than 200 DM",
    "4- No Account"
]

# Create the boxplot
ax = sns.boxplot(
    data=df,
    x=attribute,
    y=target,
    palette="viridis",
    order=desired_order
)

# Set the descriptive labels on the x-axis
ax.set_xticklabels(labels)

plt.title(f"Distribution of {target} by {attribute}")
plt.xlabel("Account Balance")
plt.ylabel(f"{target} (DM)")
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Duration of Credit_vs_Account Balance.png', dpi=300, bbox_inches='tight')
plt.show()

attribute = 'Payment Status of Previous Credit'
target = 'Credit Amount'

plt.figure(figsize=(12, 8))

# Define your order and labels
desired_order = ["0", "1", "2", "3", "4"]
labels = ["0- No Credits Taken",
    "1- All credits Paid Back duly",
    "2- Existing credits paid back duly",
    "3- Delay paying off in past ",
    "4- Critical Account"
]

# Create the boxplot
ax = sns.boxplot(
    data=df,
    x=attribute,
    y=target,
    palette="viridis",
    order=desired_order
)

# Set the descriptive labels on the x-axis
ax.set_xticklabels(labels)

plt.title(f"Distribution of {target} by {attribute}")
plt.xlabel("Payment Status of Previous Credit", fontweight='bold')
plt.ylabel(f"{target}")
plt.tight_layout()
plt.xticks(rotation=45, ha='right')
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Credit Amount_vs_Payment Status.png', dpi=300, bbox_inches='tight')
plt.show()

attribute = 'Payment Status of Previous Credit'
target = 'Duration of Credit (month)'

plt.figure(figsize=(12, 8))

# Define your order and labels
desired_order = ["0", "1", "2", "3", "4"]
labels = ["0- No Credits Taken",
    "1- All credits Paid Back duly",
    "2- Existing credits paid back duly",
    "3- Delay paying off in past ",
    "4- Critical Account"]


# Create the boxplot
ax = sns.boxplot(
    data=df,
    x=attribute,
    y=target,
    palette="viridis",
    order=desired_order
)

# Set the descriptive labels on the x-axis
ax.set_xticklabels(labels)

plt.title(f"Distribution of {target} by {attribute}")
plt.xlabel("Payment Status of Previous Credit", fontweight='bold')
plt.ylabel(f"{target}")
plt.tight_layout()
plt.xticks(rotation=45, ha='right')
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Duration of Credit_vs_Payment Status.png', dpi=300, bbox_inches='tight')
plt.show()

"""Scatterplot"""

plt.scatter(df['Age (years)'], df['Credit Amount'], color="blue")
plt.title("Scatterplot of Credit Amount by Age")
plt.xlabel('Age (years)')
plt.ylabel('Credit Amount')
plt.show()

model1 = smf.ols("Q('Credit Amount') ~ Q('Duration of Credit (month)')", data=df).fit()
print(model1.summary())

plt.figure(figsize=(10, 6))

# common_norm=False ensures the areas are comparable even if group sizes differ
sns.kdeplot(data=df, x='Age (years)', hue='Creditability', fill=True, common_norm=False, palette='coolwarm')

plt.title('Age Density: Good vs. Bad Credit', fontsize=14)
plt.xlabel('Age (Years)')
plt.ylabel('Density')
#Commented it due to the path error
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Age_Density_Good _vs_Bad_Credit.png', dpi=300, bbox_inches='tight')
plt.show()

print("""
Age is not a good predictor of Good vs Bad Credit

""")


plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='Duration of Credit (month)', hue='Creditability', fill=True, common_norm=False, palette='coolwarm')
plt.title('Duration of Credit (month) Density: Good vs. Bad Credit', fontsize=14)
plt.xlabel('Duration of Credit (month)')
plt.ylabel('Density')

#Commented due to the bad file path
plt.xticks(range(0, 91, 10))
plt.legend(title='Creditability', labels=['0-Bad', '1-Good'])
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Duration_of_Credit_Density_Good _vs_Bad Credit.png', dpi=300, bbox_inches='tight')

plt.show()

print("""
There is not a lot of separation between Good and Bad Credit based on Duration of Credit.
However, as the duration increases the likelihood of bad credit slightly increases

""")

plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='Credit Amount', hue='Creditability', fill=True, common_norm=False, palette='coolwarm')
plt.title('Credit Amount Density: Good vs. Bad Credit', fontsize=14)
plt.xlabel('Credit Amount')
plt.ylabel('Density')

#Please Remove the comment
plt.legend(title='Creditability', labels=['0-Bad', '1-Good'])
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Credit_Amount_Density_Good _vs_Bad Credit.png', dpi=300, bbox_inches='tight')
plt.show()

print("""
There is almost no separation between Good and Bad Credit based on Credit Amount.
However, out past 15M+ DM we can see that there are more cases (though a small number)
of bad credit indicating that loans are riskier at these higher amounts

""")

#1. Set the figure size
plt.figure(figsize=(12, 8))

# 2. Create the Bar Plot AND assign it to 'ax'

ax = sns.barplot(x='Credit Amount', y='Occupation', data=df, palette='magma', errorbar=None)

# 3. Add labels and title
plt.title('Average Credit Amount by Occupation', fontsize=15, fontweight='bold')
plt.xlabel('Average Credit Amount (DM)')
plt.ylabel('Occupation Type')

# Define labels in the exact order they appear on the numeric y-axis

labels = [
    "1: Unemployed/Unskilled non-resident",
    "2: Unskilled resident",
    "3: Skilled employee / official",
    "4: Management/Self-employed/Highly qualified"
]

# Apply the labels to the 'ax' object
ax.set_yticklabels(labels)

plt.show()

"""Box Plots, Frequency Distributions, etc."""

import seaborn as sns
import matplotlib.pyplot as plt
sns.boxplot(x= 'Credit Amount', y = 'Sex & Marital Status', data = df, palette = "pastel")
plt.title("Credit amount by Sex and Marital Status")
#Comented this line because of the file not found error
#plt.savefig('/content/drive/MyDrive/CIND_119_Group_Assignment/EDA-Images/Credit_Box_Plot.png', dpi=300, bbox_inches='tight')
plt.show()

sns.boxplot(x= 'Credit Amount', y = 'Foreign Worker', data = df, palette = "pastel")
plt.title("Credit amount by Foreign Worker")
plt.show()

sns.boxplot(x= 'Credit Amount', y = 'Creditability', data = df, palette = "pastel")
plt.title("Credit amount by Creditability")
plt.show()

_attribute = 'Creditability'

plt.figure(figsize=(10, 6))
# Create the plot
ax = sns.countplot(data=df, y=_attribute, palette="viridis", hue=_attribute, legend=False)

# Define labels in order (match the numbers on your y-axis)

labels = ["1-Good", "0-Bad", ]

# Set the new labels on the y-axis
ax.set_yticklabels(labels)

plt.title(f"Frequency Distribution of {_attribute}")
plt.xlabel("Number of Applicants")
plt.ylabel(_attribute)
#plt.savefig('/content/drive/MyDrive/CIND 119 Group Assignment/EDA- Images/ Creditability_Good _vs_Bad Credit.png', dpi=300, bbox_inches='tight')
plt.show()

attribute = 'Account Balance'
target = 'Credit Amount' # The numerical value you want to average

plt.figure(figsize=(10, 6))

# Define the order and the matching descriptive labels
desired_order = ["1", "2", "3", "4"]
labels = [
    "Less than 0 DM",
    "0 to 200 DM",
    "Greater than 200 DM",
    "No Account"
]

# Use sns.barplot instead of countplot
# x is the categorical attribute, y is the numerical value
ax = sns.barplot(
    data=df,
    x=attribute,
    y=target,
    palette="viridis",
    hue=attribute,
    legend=False,
    order=desired_order
)

# Set the descriptive labels on the x-axis
ax.set_xticklabels(labels)

plt.title(f"Average {target} by {attribute}")
plt.xlabel(attribute)
plt.ylabel(f"Mean {target} (DM)")

plt.show()

attribute = 'Account Balance'

plt.figure(figsize=(10, 6))

desired_order = [
    "1", "2", "3","4"
    ]
# Create the plot
ax = sns.countplot(data=df, y=attribute, palette="viridis", hue=attribute, legend=False, order=desired_order )

# Define labels in order (match the numbers on your y-axis)
# Based on your image order: 2, 3, 4, 1
labels = ["1- Less than 0 DM",
    "2- Between 0 and 200 DM",
    "3- Greater than 200 DM",
    "4-No Checking Account"]

# Set the new labels on the y-axis
ax.set_yticklabels(labels)

plt.title(f"Frequency Distribution of {attribute}")
plt.xlabel("Number of Applicants")
plt.ylabel(attribute)
plt.show()

attribute = 'Sex & Marital Status'

plt.figure(figsize=(10, 6))
# Create the plot
ax = sns.countplot(data=df, y=attribute, palette="viridis", hue=attribute, legend=False)

# Define labels in order (match the numbers on your y-axis)
# Based on your image order: 2, 3, 4, 1
labels = ["2-Female: Div/Sep/Mar", "3-Male: Single", "4-Male: Mar/Wid", "1-Male: Div/Sep"]

# Set the new labels on the y-axis
ax.set_yticklabels(labels)

plt.title(f"Frequency Distribution of {attribute}")
plt.xlabel("Number of Applicants")
plt.ylabel(attribute)
plt.show()

sns.boxplot(x= 'Age (years)', y = 'Creditability', data = df, palette = "pastel")
plt.title("Creditability by Age (years)")
plt.show()

"""Pearson Correlation of Selected Numeric Attributes"""

df_numeric = df[['Age (years)', 'Credit Amount', 'Duration of Credit (month)']]

# Calculate the correlation matrix
corr = df_numeric.corr(method="pearson")

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=False, cmap="coolwarm", center=0)
plt.title("Pearson Correlation (German Credit data)")
plt.show()

print("""
Credit Amount and Duration of Credit have a moderate to strong relationship. Which makes sense since the larger the loan the longer you may need to pay it off./n
Age does not seem to be a factor in the size of the Credit or the duration of the credit. """)

# 1. Identify non-numeric (object) columns
cat_cols = df.select_dtypes(include=['object']).columns

# 2. Set up the figure size based on the number of columns found
plt.figure(figsize=(15, 20))

# 3. Loop through each column and create a subplot
for i, col in enumerate(cat_cols, 1):
    plt.subplot(len(cat_cols)//2 + 1, 2, i) # Arrange in 2 columns
    sns.countplot(y=col, data=df, palette='viridis', hue=col, legend=False)
    plt.title(f'Distribution of {col}')
    plt.tight_layout()

plt.show()

print("""

SOMETHING THAT STANDS OUT. The distribution of Foreign Workers is almost entirely "1= Yes Foreign worker". Only 3.7% of the total rows are "2- No Foreign Worker" """)

"""Distributions of the Numerics Attributes"""

import matplotlib.pyplot as plt

# Choose the column you want to check
col_1 = 'Age (years)'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_1], kde=True, color="skyblue")
plt.title(f"Distribution of {col_1}")
plt.show()

col_2 = 'Duration of Credit (month)'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_2], kde=True, color="skyblue")
plt.title(f"Distribution of {col_2}")
plt.show()

col_3 = 'Credit Amount'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_3], kde=True, color="skyblue")
plt.title(f"Distribution of {col_3}")
plt.show()

col_4 = 'Instalment per cent'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_4], kde=True, color="skyblue")
plt.title(f"Distribution of {col_4}")
plt.show()

col_5 = 'No of Credits at this Bank'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_5], kde=True, color="skyblue")
plt.title(f"Distribution of {col_5}")
plt.show()

col_6 = 'No of dependents'

plt.figure(figsize=(8, 4))
sns.histplot(df[col_6], kde=True, color="skyblue")
plt.title(f"Distribution of {col_6}")
plt.show()

print(summary_german_data)

"""Duplicate Rows Check"""

print(f"Total duplicate rows: {df.duplicated().sum()}")

# 2. View the actual duplicate rows to inspect them
duplicate_rows = df[df.duplicated(keep=False)]
print(duplicate_rows.sort_values(by=list(df.columns[:3]))) # Sort to see them side-by-side

"""Cleaned Dataset"""

# Creating a cleaned dataframe (df_clean) where 'Instalments per cent' and 'No of Credits at this bank' are converted to objects.

df_clean = df.copy()
df_update=df.copy()

cols_to_fix = ["Instalment per cent"]
for col in cols_to_fix:
    df_clean[col] = df_clean[col].astype('object')

cols_to_fix = ["Instalment per cent"]
for col in cols_to_fix:
    df_update[col] = df_update[col].astype('object')

print(f"Raw Type: {df['Instalment per cent'].dtype}")
print(f"Cleaned Type: {df_clean['Instalment per cent'].dtype}")

"""Stats for df_clean numerical data types"""

# 2. Create the summary dataframe
# We use .select_dtypes('number') to ensure we don't try to get the mean of text
summary_numerical__df_clean = df_clean.select_dtypes('number').agg(stats_to_compute).T

# 3. Mode is tricky because one column can have multiple modes.
# We add it separately to keep the table clean.
summary_numerical__df_clean['mode'] = df_clean.select_dtypes('number').mode().iloc[0]

# 4. Rename columns for a professional look
summary_numerical__df_clean.columns = ['Mean', 'Median', 'Std Dev', 'Min', 'Max', 'Mode']

# Display the clean table
summary_numerical__df_clean

df_clean.describe()

# Choose the column you want to check
col_1 = 'Age (years)'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_1], kde=True, color="skyblue")
plt.title(f"Distribution of {col_1}")
plt.show()

col_2 = 'Duration of Credit (month)'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_2], kde=True, color="skyblue")
plt.title(f"Distribution of {col_2}")
plt.show()

col_3 = 'Credit Amount'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_3], kde=True, color="skyblue")
plt.title(f"Distribution of {col_3}")
plt.show()

col_6 = 'No of dependents'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_6], kde=True, color="skyblue")
plt.title(f"Distribution of {col_6}")
plt.show()

# log normalizing 'Credit Amount", Age (years), 'Duration of Credit' to create a normalized distrbution in order to help the Naive Bayes model.


import numpy as np


# continuous numeric columns that need log-transforming
cols_to_log = ['Credit Amount', 'Age (years)', 'Duration of Credit (month)']

for col in cols_to_log:
    # Overwriting the original column with its log1p version
    df_clean[col] = np.log1p(df_clean[col])

# Verify the values have changed (they should now be small, like 2.0 to 9.0)
print(df_clean[cols_to_log].head())

import numpy as np


# continuous numeric columns that need log-transforming
cols_to_log = ['Credit Amount', 'Age (years)', 'Duration of Credit (month)']

for col in cols_to_log:
    # Overwriting the original column with its log1p version
    df_update[col] = np.log1p(df_update[col])

# Verify the values have changed (they should now be small, like 2.0 to 9.0)
print(df_update[cols_to_log].head())

col_1 = 'Age (years)'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_1], kde=True, color="skyblue")
plt.title(f"Distribution of {col_1}")
plt.show()

col_2 = 'Duration of Credit (month)'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_2], kde=True, color="skyblue")
plt.title(f"Distribution of {col_2}")
plt.show()

col_3 = 'Credit Amount'

plt.figure(figsize=(8, 4))
sns.histplot(df_clean[col_3], kde=True, color="skyblue")
plt.title(f"Distribution of {col_3}")
plt.show()

print(df_clean)

"""**Naive Bayes Classifier on Updated Cleaned Dataset**"""

#Importing All the Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Target Column
y=df_update['Creditability']
x = df_update.drop('Creditability', axis=1)

#Train/Split Data
#Training Set = 80% , Testing Set=20%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="viridis")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""**Naive Bayes on Updated Cleaned Dataset using selected Features Only**"""

#Importing All the Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Target Column
y=df_update['Creditability']
x = df_update.drop(['Creditability','Sex & Marital Status','Type of apartment','Foreign Worker','Value Savings/Stocks','No of dependents','Concurrent Credits',
                   'Duration in Current address','Length of current employment','Instalment per cent','No of Credits at this Bank','Age (years)',
                   'Occupation','Telephone'], axis=1)

#Train/Split Data
#Training Set = 80% , Testing Set=20%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="viridis")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""**NAIVE BAYES CLASSIFIER PERFORMED ON THE CLEANED DATA SET**"""

# Applying Naive Bayes Classifier on the cleaned Data Set

#Importing All the Machine Learning Libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Target Column
y=df_clean['Creditability']
x = df.drop('Creditability', axis=1)

#Train/Split Data
#Training Set = 80% , Testing Set=20%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))


#Predict Risk for a new Customer
new_customer = [[
    2,      # Account Balance
    3.0,    # Duration of Credit (month)
    3,      # Payment Status of Previous Credit
    1,      # Purpose
    8.2,    # Credit Amount
    2,      # Value Savings/Stocks
    4,      # Length of current employment
    3.0,    # Instalment per cent
    2,      # Sex & Marital Status
    1,      # Guarantors
    3,      # Duration in Current address
    2,      # Most valuable available asset
    3.5,    # Age (years)
    2,      # Concurrent Credits
    2,      # Type of apartment
    1.0,    # No of Credits at this Bank
    3,      # Occupation
    1.0,    # No of dependents
    1,      # Telephone
    1       # Foreign Worker
]]

prediction = model.predict(new_customer)
if prediction ==1:
  print("High Risk Customer")
else:
  print("Low Risk Customer")

"""*Our Model predicted the Credibility of a New Customer with 76% Accuracy*

**After Analysis we decided to drop the last 2 attributes from our dataset to improve its overall efficiency since the phone number has logically no say in the credibility and distribution of foreign workers is entirely the same throughout our dataset.**
"""

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 80% , Testing Set=20%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""*However, the overall accuracy didn't improve much after removing the two attributes i.e Phone Number & Foreign Workers hence we can remove these 2 attributes to simplify our model since phone number has low corelation with target and Foreign worker feature is constant throughout our dataset and these features add noise to our model and not signal*

**Reevaluating our model based on 70% Training and 30% Test**
"""

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 70% , Testing Set=30%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""**The overall accuracy didnt change**

**Reevaluating our model based on 60% Training and 40% Test**
"""

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 60% , Testing Set=40%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.4, random_state=42
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""Shuffling the Dataset"""

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 70% , Testing Set=30%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, shuffle = True,random_state=56
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""**Using Stratified Split** Keeps class distribution balanced in train/test"""

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 70% , Testing Set=30%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y,shuffle = True,random_state=56
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""*Result: After using the Startified split our model become less accurate*

**Oversampling Method: Increasing the Minority Class i.e Bad Credit to be able to predict the Bad Credit more accurately**

#Target Column
y=df_clean['Creditability']
x = df.drop(['Creditability','Telephone','Foreign Worker'], axis=1)

from sklearn.utils import resample

# Combining X and y
df_combined = x.copy()
df_combined['target'] = y

# Separating classes
good_credit = df_combined[df_combined['target'] == 1]
bad_credit = df_combined[df_combined['target'] == 0]

# Upsampling bad class
bad_upsampled = resample(
    bad_credit,
    #Allow Duplicates
    replace=True,
    #Match Majority Class i.e Good Credit
    n_samples=len(good_credit),
    random_state=42
)

# Combining back
df_balanced = pd.concat([good_credit, bad_upsampled])

# Shuffle dataset
df_balanced = df_balanced.sample(frac=1, random_state=42)

#Train/Split Data
#Training Set = 70% , Testing Set=30%

x_bal = df_balanced.drop("Creditability", axis=1)
y_bal = df_balanced["Creditability"]

X_train, X_test, y_train, y_test = train_test_split(
    x_bal, y_bal, test_size=0.3, stratify=y,shuffle = True,random_state=56
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

Using SMOTE Technique to solve class imbalance problem and creating synthethic samples of our minority class to remove the class imbalance
"""

#pip install imbalanced-learn
from imblearn.over_sampling import SMOTE
df_clean.info()

#Splitting Features and Target
x=df_clean.drop('Creditability',axis=1)
y=df_clean['Creditability']

print("Before SMOTE:")
print(y.value_counts())

#Test and Train Split -> 80% Test and 20% Train
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

#Applying SMOTE on the Training Data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

#Note that after the SMOTE Technique our dataset is well balanced

#Training the model
model = GaussianNB()
model.fit(X_train_smote, y_train_smote)

y_pred = model.predict(X_test)

#Evaluate our model
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

"""Results from SMOTE Method: After applying the SMOTE technique and tarining our model on the balanced dataset, we can see that we were able to significantly reduce the false negatives from our dataset and the model was better able to predict the bad credit, however false positives also significantly increased in our model, so its a tradeoff worth debating
Recall for Class 0 i.e Bad Credit increased Significantly and the accuracy of our model dropped to 63%

Dropping the Foreign Worker and Telephone Columns and Re-evaluating our model
--

Optimal Approach with 68% Accuracy
balanced ratio of False Positives and False Negatives
"""

#Splitting Features and Target
x=df_clean.drop('Creditability',axis=1)
y=df_clean['Creditability']

print("Before SMOTE:")
print(y.value_counts())

#Test and Train Split -> 80% Test and 20% Train
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

#Applying SMOTE on the Training Data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

#Note that after the SMOTE Technique our dataset is well balanced

#Training the model
model = GaussianNB()
model.fit(X_train_smote, y_train_smote)

y_pred = model.predict(X_test)

#Evaluate our model
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))
#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

"""**Removing duplicates from our dataset**"""

# Convert target
df_clean["Creditability"] = df_clean["Creditability"].astype(int)

# Remove duplicates
df_clean= pd.get_dummies(df_clean, drop_first=True)



#Splitting Features and Target
x=df_clean.drop('Creditability',axis=1)
y=df_clean['Creditability']

print("Before SMOTE:")
print(y.value_counts())

#Test and Train Split -> 80% Test and 20% Train
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

#Applying SMOTE on the Training Data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

#Note that after the SMOTE Technique our dataset is well balanced

#Training the model
model = GaussianNB()
model.fit(X_train_smote, y_train_smote)

y_pred = model.predict(X_test)

#Evaluate our model
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

"""**Feature Selection**"""

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler

# Convert target
df_clean["Creditability"] = df_clean["Creditability"].astype(int)

# Remove duplicates
df_clean= pd.get_dummies(df_clean, drop_first=True)



#Splitting Features and Target
x=df_clean.drop('Creditability',axis=1)
y=df_clean['Creditability']

print("Before SMOTE:")
print(y.value_counts())

#Test and Train Split -> 80% Test and 20% Train
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

selector = SelectKBest(score_func=f_classif, k=15)

X_train_selected = selector.fit_transform(X_train_scaled, y_train)
X_test_selected = selector.transform(X_test_scaled)

selected_features = x.columns[selector.get_support()]

print("Selected Features:")
print(selected_features)

#Applying SMOTE on the Training Data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_selected, y_train)

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

#Note that after the SMOTE Technique our dataset is well balanced

#Training the model
model = GaussianNB()
model.fit(X_train_smote, y_train_smote)

y_pred = model.predict(X_test_selected)

#Evaluate our model
print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

from sklearn.feature_selection import mutual_info_classif
X = df.drop("Creditability", axis=1)
y = df["Creditability"]

mi_scores = mutual_info_classif(X, y)

# Create DataFrame
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": mi_scores
})

# Sort
feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

plt.figure(figsize=(10,6))
plt.barh(feature_importance["Feature"], feature_importance["Importance"])

plt.xlabel("Importance Score")
plt.title("Feature Importance (Mutual Information)")
plt.gca().invert_yaxis()

plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True)

plt.title("Correlation with Target")
plt.show()

#corelation matrix on the cleaned dataset
X = df_update.drop("Creditability", axis=1)
y = df_update["Creditability"]

mi_scores = mutual_info_classif(X, y)

# Create DataFrame
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": mi_scores
})

# Sort
feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

plt.figure(figsize=(10,12))
plt.barh(feature_importance["Feature"], feature_importance["Importance"])

plt.xlabel("Importance Score")
plt.title("Feature Importance (Mutual Information)")
plt.gca().invert_yaxis()

plt.show()

plt.figure(figsize=(16,8))
sns.heatmap(df.corr(), annot=True)

plt.title("Correlation with Target")
plt.show()

#Target Column
y=df_clean['Creditability']
x = df.drop(['Telephone','Foreign Worker'], axis=1)

#Train/Split Data
#Training Set = 70% , Testing Set=30%

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, shuffle = True,random_state=56
)

#Training the Naive Bayes Model
model = GaussianNB()
model.fit(X_train, y_train)

#Making Predictions on the Test Set
y_pred = model.predict(X_test)

#Checking some predictions
#print(y_pred[:10])

#Evaluating the Model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

#Calculate the Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
print("Confusion Matrix:")
print(conf_matrix)

#Classification Report to find precison, recall and f1 score
print(classification_report(y_test, y_pred))

"""# Predictive Modeling (Classification).

# Decision Tree. Train-Test Split (70/30)
"""

# First split the data into train and test set
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
# Our class column is Creditability here and everything else will be used as features
class_col_name='Creditability'
#df_update
feature_names=df.columns[df.columns != class_col_name ]
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(df.loc[:, feature_names], df[class_col_name], test_size=0.3,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz

# Define the actual class names based on the numeric target (0 and 1) in y
# Assuming 0 is 'Bad Credit' and 1 is 'Good Credit' based on the Data_Dictionary
class_names_for_viz = ['Bad Credit', 'Good Credit']

# Get feature names from the X_train used to fit the classifier
feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True) # Added rounded for better visual

# Plot tree
graph = graphviz.Source(dot_data, format="png")
graph

""""This Decision Tree Classifier is a predictive model used to assess credit risk, categorizing applicants as either 'Good Credit' (blue) or 'Bad Credit' (orange). Starting from the most critical feature—Status of Checking Account—the model branches through a series of logical tests on variables such as Duration of Credit, Savings Status, and Credit Amount.

Each node displays Gini Impurity to measure the 'purity' of the split, the number of samples analyzed at that stage, and a value breakdown showing the distribution between classes. Ultimately, the tree provides a transparent, rule-based map that identifies which financial factors most strongly influence an applicant's creditworthiness."
"""

# Let's make the prdictions on the test set  that we set aside earlier using the trained tree
y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

#print precision, recall, and accuracy from the perspective of each of the class (0 and 1 for German dataset)
from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""The model achieved an accuracy of 77%.

The confusion matrix shows that the model correctly classified most of the good credit instances but struggled with identifying bad credit cases. The classification report further confirms this, with a high recall of 0.96 for good credit but a low recall of 0.32 for bad credit.

This indicates that the model is biased toward the majority class(Good customers) and may not perform well in detecting risky customers.

# Re evaluating our model based on 80% Training and 20% Test
"""

# First split the data into train and test set
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
# Our class column is Creditability here and everything else will be used as features
class_col_name='Creditability'

feature_names=df.columns[df.columns != class_col_name ]
# 80% training and 20% test
X_train, X_test, y_train, y_test = train_test_split(df.loc[:, feature_names], df[class_col_name], test_size=0.2,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz

# Define the actual class names based on the numeric target (0 and 1) in y
# Assuming 0 is 'Bad Credit' and 1 is 'Good Credit' based on the Data_Dictionary
class_names_for_viz = ['Bad Credit', 'Good Credit']

# Get feature names from the X_train used to fit the classifier
feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True) # Added rounded for better visual

# Plot tree
graph = graphviz.Source(dot_data, format="png")
graph

"""This Decision Tree Classifier uses an 80/20 train-test split, meaning it was trained on 800 samples to predict credit risk. It begins its logic at the Account Balance node but features a more complex branching structure, incorporating a wider variety of variables such as Duration of Credit, Age, and Length of Current Employment. The model segments data based on Gini Impurity to maximize classification "purity," with blue nodes representing "Good Credit" and orange nodes indicating "Bad Credit." By utilizing a larger training set (80%), this version of the model potentially offers a more nuanced set of rules for determining creditworthiness across its many leaf nodes."""

# Let's make the prdictions on the test set  that we set aside earlier using the trained tree
y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

#print precision, recall, and accuracy from the perspective of each of the class (0 and 1 for German dataset)
from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""The model achieved an accuracy of 70% on the test dataset.

For the positive class (Good Credit): The model achieved a precision of 0.76, meaning about 76% of the customers predicted as "good" actually were. The recall of 0.86 indicates that the model successfully identified the vast majority of all good credit cases in the data.

For the negative class (Bad Credit): The recall is very low at 0.30, which means the model only caught 30% of the actual risky customers. Furthermore, the precision is 0.46, indicating that when the model flags someone as "bad credit," it is wrong more than half the time.

This shows that while the model is good at finding reliable customers, it is critically weak at detecting risky ones, missing 70% of potential bad credit cases.

# IMPORTANT INSIGHT

"Compared to the 70/30 split, the 80/20 split model shows a significant decline in performance. Not only did the overall accuracy drop from 77% to 70%, but the model's ability to identify high-risk customers (Class 0) also weakened. This suggests that the additional training data in the 80/20 split did not help the Decision Tree learn the patterns of bad credit; instead, it likely increased the model's bias toward the majority class (good credit), making it a less reliable tool for risk assessment."

# Dropping attributes and Re-evaluating our model

After reviewing the data, we decided to drop the last two variables. We removed the phone numbers because they don't affect credit scores, and the foreign worker status because the values were the same for everyone.

This step allows us to test whether removing these irrelevant features enhances the model's accuracy and overall efficiency.
"""

x = df.drop(['Creditability','Telephone','Foreign Worker','Sex & Marital Status', 'Duration in Current address', 'No of dependents'], axis=1)

from sklearn.model_selection import train_test_split
class_col_name='Creditability'

feature_names=df.columns[df.columns != class_col_name ]
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(df.loc[:, feature_names], df[class_col_name], test_size=0.3,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz

# Define the actual class names based on the numeric target (0 and 1) in y
# Assuming 0 is 'Bad Credit' and 1 is 'Good Credit' based on the Data_Dictionary
class_names_for_viz = ['Bad Credit', 'Good Credit']

# Get feature names from the X_train used to fit the classifier
feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True) # Added rounded for better visual

# Plot tree
graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""The overall accuracy of the model does not change."""

x = df.drop(['Creditability','Telephone','Foreign Worker','Sex & Marital Status', 'Duration in Current address', 'No of dependents'], axis=1)

from sklearn.model_selection import train_test_split
class_col_name='Creditability'

feature_names=df.columns[df.columns != class_col_name ]
# 80% training and 20% test
X_train, X_test, y_train, y_test = train_test_split(df.loc[:, feature_names], df[class_col_name], test_size=0.2,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz
class_names_for_viz = ['Bad Credit', 'Good Credit']
feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True)
# Plot tree
graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""# Decision Tree on Updated Cleaned Dataset. Train-Test Split (70/30)"""

from sklearn.model_selection import train_test_split
class_col_name='Creditability'
#df_update
feature_names=df_update.columns[df_update.columns != class_col_name ]
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(df_update.loc[:, feature_names], df_update[class_col_name], test_size=0.3,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz
class_names_for_viz = ['Bad Credit', 'Good Credit']

# Get feature names from the X_train used to fit the classifier
feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True) # Added rounded for better visual

# Plot tree
graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

#print precision, recall, and accuracy from the perspective of each of the class (0 and 1 for German dataset)
from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""# Decision Tree on Updated Cleaned Dataset. Train-Test Split (80/20)"""

from sklearn.model_selection import train_test_split
class_col_name='Creditability'

feature_names=df_update.columns[df_update.columns != class_col_name ]
# 80% training and 20% test
X_train, X_test, y_train, y_test = train_test_split(df_update.loc[:, feature_names], df_update[class_col_name], test_size=0.2,random_state=1)

from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz
class_names_for_viz = ['Bad Credit', 'Good Credit']

feature_names_for_viz = X_train.columns.tolist()

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True)
graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""# Retraining the Model Using the Top 7 Most Important Features

# 70/30 Split
"""

x = df_update.drop(['Creditability', 'Telephone', 'Occupation', 'Age (years)', 'No of Credits at this Bank', 'Instalment per cent', 'Length of current employment', 'Duration in Current address', 'Concurrent Credits', 'No of dependents', 'Value Savings/Stocks', 'Foreign Worker', 'Type of apartment', 'Sex & Marital Status'], axis=1)

from sklearn.model_selection import train_test_split
class_col_name='Creditability'
feature_names=df_update.columns[df_update.columns != class_col_name ]
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(df_update.loc[:, feature_names], df_update[class_col_name], test_size=0.3,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz
class_names_for_viz = ['Bad Credit', 'Good Credit']

feature_names_for_viz = X_train.columns.tolist()
dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True)

graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""# 80/20 Splits"""

x = df_update.drop(['Creditability', 'Telephone', 'Occupation', 'Age (years)', 'No of Credits at this Bank', 'Instalment per cent', 'Length of current employment', 'Duration in Current address', 'Concurrent Credits', 'No of dependents', 'Value Savings/Stocks', 'Foreign Worker', 'Type of apartment', 'Sex & Marital Status'], axis=1)

from sklearn.model_selection import train_test_split
class_col_name='Creditability'
feature_names=df_update.columns[df_update.columns != class_col_name ]
# 80% training and 20% test
X_train, X_test, y_train, y_test = train_test_split(df_update.loc[:, feature_names], df_update[class_col_name], test_size=0.2,random_state=1)

from sklearn import tree

clf = tree.DecisionTreeClassifier(max_depth=5)
clf = clf.fit(X_train, y_train)
print("Successfully trained the decision tree...")

import graphviz
class_names_for_viz = ['Bad Credit', 'Good Credit']

feature_names_for_viz = X_train.columns.tolist()
dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names_for_viz,
                                class_names=class_names_for_viz,
                                filled=True,
                                rounded=True)

graph = graphviz.Source(dot_data, format="png")
graph

y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test, y_pred)
print ("Confusion Matrix")
print(cf)
tn, fp, fn, tp=cf.ravel()
print ("TP: ", tp,", FP: ", fp,", TN: ", tn,", FN:", fn)

from sklearn.metrics import classification_report
from sklearn import metrics

print(classification_report(y_test, y_pred))

"""Abstract / Summary

In this project, we take on the role of data scientists to address a real-world financial problem faced by banking institutions: credit risk assessment. The primary aim of this project is to develop an accurate and reliable predictive model that can classify customers as high risk or low risk, and support decision-making on whether a loan should be approved or rejected. Accurate credit risk prediction is essential for banks, as poor lending decisions can lead to financial losses and increased default rates, while overly strict policies may result in missed business opportunities.

The dataset used in this project is the German Credit dataset, which contains 1,000 customer records and 21 attributes describing various financial and demographic characteristics. These attributes provide valuable insights into customer behavior and financial status, which are critical for identifying patterns associated with credit risk.

To accomplish the project objectives, we used Python for data preprocessing, analysis, and machine learning model development, and Tableau for data visualization and exploratory analysis. The project follows a structured approach, including data preparation, exploratory data analysis (EDA), predictive modeling, and evaluation.

For predictive modeling, we applied supervised machine learning classification techniques, specifically Decision Tree and Naïve Bayes algorithms, to build models that classify customers based on their creditworthiness. The performance of these models is evaluated and compared to determine the most effective approach.

Therefore, developing an accurate and reliable predictive model for credit risk classification is essential to support better financial decision-making and improve overall banking performance.
"""